services:
  telegram-bot-api:
    image: evilfreelancer/docker-telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_STAT: "true"
      TELEGRAM_LOCAL: "true"
      TELEGRAM_VERBOSITY: 1
      TELEGRAM_MAX_FILESIZE: 2000000000
    volumes:
      - /var/lib/telegram-bot-api:/var/lib/telegram-bot-api
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  audio-merger-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-merger-bot
    restart: unless-stopped
    depends_on:
      telegram-bot-api:
        condition: service_healthy
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      LOCAL_TELEGRAM_API_ROOT: "http://telegram-bot-api:8081"
      FFMPEG_PATH: /usr/bin/ffmpeg
      FFPROBE_PATH: /usr/bin/ffprobe
      CLEANUP_DIRECTORY: /var/lib/telegram-bot-api
      CLEANUP_INTERVAL_HOURS: 24
      NODE_ENV: production
    volumes:
      - /var/lib/telegram-bot-api:/var/lib/telegram-bot-api
