services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    hostname: localhost
    container_name: telegram-bot-api
    restart: unless-stopped
    user: "0:0"
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: 1
      TELEGRAM_HTTP_IP_ADDRESS: 0.0.0.0
      TELEGRAM_HTTP_PORT: 8081
      TELEGRAM_MAX_FILESIZE: 2000000000
    volumes:
      - /var/lib/telegram-bot-api:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
      - "8082:8082"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8081/bot${TELEGRAM_TOKEN}/getMe || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  audio-merger-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-merger-bot
    restart: unless-stopped
    user: "0:0"
    depends_on:
      telegram-bot-api:
        condition: service_healthy
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      LOCAL_TELEGRAM_API_ROOT: "http://localhost:8081"
      FFMPEG_PATH: /usr/bin/ffmpeg
      FFPROBE_PATH: /usr/bin/ffprobe
      CLEANUP_INTERVAL_HOURS: 24
      CLEANUP_DIRECTORY: /var/lib/telegram-bot-api
      NODE_ENV: production
    volumes:
      - /var/lib/telegram-bot-api:/var/lib/telegram-bot-api

volumes:
  telegram-bot-api-data: # Define the named volume
