name: Deploy Audio Merger Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy audio merger bot to antiX server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies and build
        run: |
          if [ -e package-lock.json ]; then
            npm ci
          else
            npm install
          fi
          npm run build

      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Configure SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_AUDIO_BOT }}" > ~/.ssh/github-audio-bot-deploy
          chmod 600 ~/.ssh/github-audio-bot-deploy
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy files to server
        run: |
          # Create directory structure if it doesn't exist
          ssh -i ~/.ssh/github-audio-bot-deploy -o StrictHostKeyChecking=no saksham@${{ secrets.DEPLOY_HOST }} "
            mkdir -p /home/saksham/Desktop/telegram-bots/audio-merger-bot/dist
          "

          # Transfer built files
          rsync -avz --delete -e "ssh -i ~/.ssh/github-audio-bot-deploy -o StrictHostKeyChecking=no" \
            dist/ saksham@${{ secrets.DEPLOY_HOST }}:/home/saksham/Desktop/telegram-bots/audio-merger-bot/dist/

          # Transfer configuration files
          rsync -avz -e "ssh -i ~/.ssh/github-audio-bot-deploy -o StrictHostKeyChecking=no" \
            package.json ecosystem.config.js saksham@${{ secrets.DEPLOY_HOST }}:/home/saksham/Desktop/telegram-bots/audio-merger-bot/

      - name: Deploy and restart service
        run: |
          ssh -i ~/.ssh/github-audio-bot-deploy -o StrictHostKeyChecking=no -o ConnectTimeout=60 saksham@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd /home/saksham/Desktop/telegram-bots/audio-merger-bot
            
            # Update code from repository
            timeout 60 git pull origin master || echo "Git pull failed or timed out, continuing with uploaded files"
            
            # Install production dependencies
            timeout 120 npm ci --production
            
            # Setup cleanup cron job if it doesn't exist
            if ! crontab -l 2>/dev/null | grep -q 'npm run cleanup'; then
              (crontab -l 2>/dev/null; echo '0 2 * * * cd /home/saksham/Desktop/telegram-bots/audio-merger-bot && npm run cleanup >> /var/log/telegram-cleanup.log 2>&1') | crontab -
              echo "Cleanup cron job added"
            fi
            
            # Handle PM2 process management
            if pm2 describe audio-merger-bot > /dev/null 2>&1; then
              echo "Process exists, restarting..."
              pm2 restart audio-merger-bot
              pm2 logs audio-merger-bot --lines 0 > /dev/null 2>&1 || true
            else
              echo "Process doesn't exist, starting fresh..."
              pm2 start ecosystem.config.js
            fi
            
            # Save PM2 configuration
            pm2 save
            
            echo "Audio merger bot deployment completed successfully!"
          EOF

      - name: Verify deployment
        run: |
          # Wait for process to fully start
          sleep 8
          ssh -i ~/.ssh/github-audio-bot-deploy -o StrictHostKeyChecking=no saksham@${{ secrets.DEPLOY_HOST }} "
            echo 'PM2 Status:'
            pm2 status audio-merger-bot
            echo ''
            echo 'Process Check:'
            ps aux | grep -E 'node.*audio-merger-bot' | grep -v grep || echo 'No matching processes found'
            echo ''
            echo 'Recent Logs:'
            pm2 logs audio-merger-bot --lines 5 --nostream || echo 'No logs available yet'
          "
